# Generated by Django 3.1.3 on 2021-01-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('module_number', models.CharField(max_length=100)),
                ('notes_file', models.FileField(upload_to='notes_files')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('module_number', models.CharField(max_length=100)),
            ],
        ),
    ]
