# Generated by Django 3.1.3 on 2021-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=150)),
                ('event_description', models.CharField(max_length=300)),
                ('event_category', models.CharField(choices=[('internships', 'Internships'), ('competitions', 'Competitions'), ('hackathons', 'Hackathons'), ('workshops', 'Workshops')], default='workshops', max_length=50)),
                ('event_details', models.TextField(max_length=5000)),
                ('event_image1', models.ImageField(upload_to='blog_images')),
                ('event_image2', models.ImageField(upload_to='blog_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
